### ISSUE TITLE
Unable to use workflow

### ISSUE THREAD

**Issue by faceleg** [raulchen/alfred-volume-control#2]
When attempting `vol 20`, I get the following output in alfred's workflow debugger:

```
[2016-06-26 22:04:23][ERROR: action.script] Traceback (most recent call last):
  File "process_operation.py", line 36, in <module>
    process_operation(sys.argv[1:])
  File "process_operation.py", line 10, in process_operation
    old = int(v.get_volume())
ValueError: invalid literal for int() with base 10: 'osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/SyncStateFinder.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist.\n6'
```

**Comment by faceleg** [comment]
Deleting `/Library/ScriptingAdditions/SyncStateFinder.osax` resolved this.
